name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fwilhe/ssg

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        mkdir src
        echo '# Hello, World2!' > src/index.md
        echo '<html><title></title>' > src/_header.html
        /bin/ssg5 src docs 'Test' 'http://www'
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git add docs
        git commit -am update
        git push
        find dst
